### ISSUE TITLE
Latest release in Arduino IDE 2.3.2 is M5StackMenuSystem 1.1.0 in April 2024

### ISSUE THREAD

**Issue by mdxs** [chhorisberger/M5StackMenuSystem#1]
**Describe the bug**
Latest release in Arduino IDE 2.3.2 is M5StackMenuSystem 1.1.0 in April 2024

**To Reproduce**
Open the Library Manager in Arduino IDE 2.3.2 and find M5StackMenuSystem
notice that it shows 3 versions: 0.9.0, 1.0.0, and 1.1.0

**Expected behavior**
Expected to find more recent releases like 1.1.1 and 1.1.2
as seen here on GitHub under M5StackMenuSystem releases,
which seem to indicate bug fixes to 1.1.0 available since 2023-10-22

Would it be possible to ensure at least 1.1.2 to be available in the Library Manager of Arduino IDE 2.3.2 ?

**Comment by mdxs** [comment]
Perhaps the version seen in the Library Manager of Arduino IDE depends on the version listed in these two locations?

https://github.com/chhorisberger/M5StackMenuSystem/blob/df514219284ed93d38ec366a70cd95674d70c9f1/library.json#L13

https://github.com/chhorisberger/M5StackMenuSystem/blob/df514219284ed93d38ec366a70cd95674d70c9f1/library.properties#L2

**Comment by chhorisberger** [comment]
Hi again mdxs.
You are absolutely right, this is very likely the reason why it only shows the 1.1 version in the Arduino IDE.

I I forgot to update those when creating the 1.2 tag.

I did update them today, let's see if it gets picked up.

**Comment by mdxs** [comment]
Do you also need to push some buttons to get a new release here on GitHub?

**Comment by chhorisberger** [comment]
Only setting a matching tag on Github

**Comment by chhorisberger** [comment]
version 1.1.3 should now be available in the Arduino IDE
