### ISSUE TITLE
M5Stack Core2 not supported?

### ISSUE THREAD

**Issue by mdxs** [chhorisberger/M5StackMenuSystem#2]
**Describe the bug**
While this works just fine on a M5Stack Core (v1) controller using M5StackMenuSystem v1.1.0 in Arduino IDE 2.3.2; it didn't work on a M5Stack Core2 controller.

**To Reproduce**
Build the BasicMenu (or AdvancedMenu) example and confirm that it works on a M5Stack Core (v1) controller. Switch to a Core2 controller, change the board and connection used; compile and upload, and it doesn't work. I did check if other code for the Core2 would be able to be uploaded and run using the Arduino IDE, which it did. It also seems that reset and some serial debug information did come through from the Core2 device, but I didn't look into detail; the menu certainly didn't show at all.

**Expected behavior**
While it might be perfectly fine to limit the support of M5StackMenuSystem to just the M5Stack Core (v1) controller, perhaps that could be made clear in the ReadMe and/or library description to help users decide on when to install/use it. So some listing of which devices are known/expected to be supported in the documentation could be an improvement to the project.

Otherwise, if it is the intention to also support M5Stack Core2 (and perhaps other M5Stack controllers), then there might be some more work to be done to make this work. I must say that I don't expect this from an open source project, I think it is already excellent that it works on Core (v1) controllers and while I will first look for an alternative that works on both controllers, I might in fact use M5StackMenuSystem on a Core (v1) for a prototype/demo that I'm working on. So thanks for what it does already.

**Comment by mdxs** [comment]
Actually, what I referred to as a M5Stack Core (v1) controller working for me is in my case a M5Stack Basic Core Kit v2.6

**Comment by chhorisberger** [comment]
Hi mdxs. Thanks for the input.
Unfortunately I currently don't have to time to actively work on the library.
But I added a note in the readme, encouraging anybody who is interested to give it a try and create a pull request for it :)

**Comment by chhorisberger** [comment]
Hi mdxs. Just to let you know, thanks to a pull request by lvlhead, Core2 devices should be supported as well, starting with the next release (1.2.0)

**Comment by mdxs** [comment]
Confirmed today with v1.4.3 that this is working on both my Core and Core2 very smoothly.
My apologies for not reporting back earlier.

**Comment by chhorisberger** [comment]
No worries. Nice to hear it works for you now
