### ISSUE TITLE
Alternative Callback Definition - Menu Set at Runtime Does Not Exit After Selecting Option

### ISSUE THREAD

**Issue by lvlhead** [chhorisberger/M5StackMenuSystem#4]
**Describe the bug**
In my app, I have a use-case for defining menu options at run-time in order to retrieve a menu position index as a result.  Currently I have an implementation that builds a subMenu at run-time using data input from the user.  The below example code shows my issue, I can use the CallbackMenuItem to get the menu position index from `menuItem.getPosition()` and the selected text from `menuItem.getText()`.  However, when attempting to use `menuItem.deactivateCallbacks()` within the  `addMenuItem` section, it fails to exit back to the previous menu. 

**To Reproduce**
```
Menu subMenuDynamicMenu("Dynamic Menu");
int selectedMenuEntry;

void dynamicMenuLoader(CallbackMenuItem& menuItem) {
    std::vector<String> options = ["Option 1", Option 2", "Option 3"];
    for (int i = 0; i < sizeof(options); i++) {
        subMenuDynamicMenu.addMenuItem(options[i], [](CallbackMenuItem& menuItem) {
            selectedMenuEntry = menuItem.getPosition() - 1;
            Serial.println(menuItem.getText()); // TODO: This prints the selected option
            menuItem.deactivateCallbacks(); // TODO: This does not drop us out of the menu
        });
    }
}
```

**Expected behavior**
`menuItem.deactivateCallbacks();` should do this already but does not in this scenario.

**Comment by chhorisberger** [comment]
> However, when attempting to use menuItem.deactivateCallbacks() within the addMenuItem section, it fails to exit back to the previous menu.

Just to be sure I understand the behaviour you are trying to achieve correctly: as soon as the user selects an submenu item, it should exit the submenu and show the main menu again?

**Comment by lvlhead** [comment]
Thank you!  I was being stubborn not remembering that `menuItem.getMenu()` existed.

With library version 1.2.1 and using the function call you provided, everything is working as I intended in my question.  I appreciate the support and updates you have provided :)
