### ISSUE TITLE
Creating multiples submenus and adding more actions buttons

### ISSUE THREAD

**Issue by Faragoz** [chhorisberger/M5StackMenuSystem#7]
Hello!

I am trying to add more than one submenu to the main menu. The error happens when I enter one of the submenus, go back to the main menu, and try to access the other submenu, at some point, the screen stops refreshing.

Here is an example to reproduce the bug using the Advanced Menu example:

```
Menu mainMenu("Main Menu");
Menu subMenu("Sub Menu");
Menu subMenu2("Sub Menu 2");

void setup() {
	M5.begin();
	M5.Power.begin();

	mainMenu.addMenuItem("One Time Callback", testOneTimeCallback);
	mainMenu.addMenuItem("Loop Callback", testLoopInitCallback, testLoopCallback);
	mainMenu.addSubMenu("Submenu", &subMenu);
	mainMenu.addSubMenu("Submenu 2", &subMenu2);
	mainMenu.addExitItem();

	subMenu.addMenuItem("Sub Menu Item #1", testOneTimeCallback);
	subMenu.addMenuItem("Sub Menu Item #2", testOneTimeCallback);
	subMenu.addMenuItem("Sub Menu Item #3", testOneTimeCallback);
	subMenu.addMenuItem("Sub Menu Item #4", testOneTimeCallback);
	subMenu.addMenuItem("Sub Menu Item #5", testOneTimeCallback);
	subMenu.addMenuItem("Sub Menu Item #6", testOneTimeCallback);

	subMenu2.addMenuItem("Sub Menu 2 Item #1", testOneTimeCallback);
	subMenu2.addMenuItem("Sub Menu 2 Item #2", testOneTimeCallback);
}
```

Additionally, I would like to know how I can add more buttons. I have an M5Stack Faces and would like to use the Gamepad to perform actions.

Thank you!

**Comment by chhorisberger** [comment]
Hi Faragoz. 

Thanks for reporting! Issue should be fixed with Release 1.4.1, which you can download from the GitHub page, or will be available in the Arduino IDE in the next few hours.

For the feature request about adding more buttons, can you create a new issue for it and explain in more detail what you would expect those buttons to do exactly, i.e. what functionality the library would have to allow?

**Comment by chhorisberger** [comment]
Also, feel free to close the issue if version 1.4.1 fixes things for you

**Comment by mdxs** [comment]
Used the `AdvancedMenu.ino` (modified 2024-06-23 in https://github.com/chhorisberger/M5StackMenuSystem/commit/528155132d96c3c472a671732c10dc274120fa0b) example with the OP proposed modification (see code in https://github.com/chhorisberger/M5StackMenuSystem/issues/7#issue-2329363420) with M5StackMenuSystem v1.4.3 (using M5Unified v0.2.0 and M5GFX v0.2.0) on a M5Stack Core2 and can confirm that in that configuration I can go into and out of Submenu and Submenu2 multiple times, use menu items within each Submenu  as well as in the main Menu and see no hick-ups (there are no issues with the screen not refreshing).

So, I think this ticket can be closed unless @Faragoz reports that it doesn't work.

**Comment by chhorisberger** [comment]
Thank you for verifying the fix @mdxs !
Will close the issue now
